[[Gnuastro]]
arch = "aarch64"
git-tree-sha1 = "219bac37ee9bd3751005d7c4fe5aabd48e05441d"
libc = "glibc"
os = "linux"

    [[Gnuastro.download]]
    sha256 = "745537f98309f004748bdc01d569a631298a162d07918236a4bab15b5bd8b927"
    url = "https://github.com/JuliaBinaryWrappers/Gnuastro_jll.jl/releases/download/Gnuastro-v0.14.0+0/Gnuastro.v0.14.0.aarch64-linux-gnu.tar.gz"
[[Gnuastro]]
arch = "aarch64"
git-tree-sha1 = "82d99c0bfb8658d928ea7b26b855590ebc517f28"
libc = "musl"
os = "linux"

    [[Gnuastro.download]]
    sha256 = "4d4f89e1783bb9730920985861253f368e29e5840e4f7d72d02f106b74daf102"
    url = "https://github.com/JuliaBinaryWrappers/Gnuastro_jll.jl/releases/download/Gnuastro-v0.14.0+0/Gnuastro.v0.14.0.aarch64-linux-musl.tar.gz"
[[Gnuastro]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f868843f397ea6cbfc03a51cbdcae735dfa39daf"
libc = "glibc"
os = "linux"

    [[Gnuastro.download]]
    sha256 = "a97c44660db411ff6e6401c15373cd58665cfe70e51b1b83a9013240c956e2e1"
    url = "https://github.com/JuliaBinaryWrappers/Gnuastro_jll.jl/releases/download/Gnuastro-v0.14.0+0/Gnuastro.v0.14.0.armv7l-linux-gnueabihf.tar.gz"
[[Gnuastro]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "331a0c43dd2a4ee2debf4f775dc51ad0a7abc962"
libc = "musl"
os = "linux"

    [[Gnuastro.download]]
    sha256 = "c99f72d473efdea257213ead91d71b64823123a99f2420b56613dca98dcb362c"
    url = "https://github.com/JuliaBinaryWrappers/Gnuastro_jll.jl/releases/download/Gnuastro-v0.14.0+0/Gnuastro.v0.14.0.armv7l-linux-musleabihf.tar.gz"
[[Gnuastro]]
arch = "i686"
git-tree-sha1 = "7965e19a3f1480fd943c513cd8f4568184deb301"
libc = "glibc"
os = "linux"

    [[Gnuastro.download]]
    sha256 = "44100072c7632f8a0c70cb0e244c97f5bdb0bc6063e2d11f87b546c9eecc74b1"
    url = "https://github.com/JuliaBinaryWrappers/Gnuastro_jll.jl/releases/download/Gnuastro-v0.14.0+0/Gnuastro.v0.14.0.i686-linux-gnu.tar.gz"
[[Gnuastro]]
arch = "i686"
git-tree-sha1 = "b16a8a1378fba0b0e2033053685a487335d21685"
libc = "musl"
os = "linux"

    [[Gnuastro.download]]
    sha256 = "650e24050a4358ea7f9a1acc2cbbd2f59b91ddaa0eea48c931f842cc7f5459b5"
    url = "https://github.com/JuliaBinaryWrappers/Gnuastro_jll.jl/releases/download/Gnuastro-v0.14.0+0/Gnuastro.v0.14.0.i686-linux-musl.tar.gz"
[[Gnuastro]]
arch = "powerpc64le"
git-tree-sha1 = "d88a552c4e6f88191169b448b41f991dd620f9c3"
libc = "glibc"
os = "linux"

    [[Gnuastro.download]]
    sha256 = "db4544a7b68cb597b8ceed7a8d8670833be59b25415565192607b0046bd1e463"
    url = "https://github.com/JuliaBinaryWrappers/Gnuastro_jll.jl/releases/download/Gnuastro-v0.14.0+0/Gnuastro.v0.14.0.powerpc64le-linux-gnu.tar.gz"
[[Gnuastro]]
arch = "x86_64"
git-tree-sha1 = "91588d45b6f90bed9ef08b07b9ecc4096822d1ce"
os = "macos"

    [[Gnuastro.download]]
    sha256 = "0d183beaddeda0de7c39740b0e072976ed8224b5bef28d5d89ed0bd2307d835b"
    url = "https://github.com/JuliaBinaryWrappers/Gnuastro_jll.jl/releases/download/Gnuastro-v0.14.0+0/Gnuastro.v0.14.0.x86_64-apple-darwin.tar.gz"
[[Gnuastro]]
arch = "x86_64"
git-tree-sha1 = "b9dfd298d9ef9fed5efa7a8db7dcfb7bc45ef84e"
libc = "glibc"
os = "linux"

    [[Gnuastro.download]]
    sha256 = "639b52ea8f225a5c619e8304808d6162bdbef9f893323db3414cbf5842ccc40d"
    url = "https://github.com/JuliaBinaryWrappers/Gnuastro_jll.jl/releases/download/Gnuastro-v0.14.0+0/Gnuastro.v0.14.0.x86_64-linux-gnu.tar.gz"
[[Gnuastro]]
arch = "x86_64"
git-tree-sha1 = "f65aff5bafa5af85c3ed64259f149c79f7a6c7b3"
libc = "musl"
os = "linux"

    [[Gnuastro.download]]
    sha256 = "45ec1df228d04cac29e78ed5144dced37d17f7cda267205fda8e95d12f639121"
    url = "https://github.com/JuliaBinaryWrappers/Gnuastro_jll.jl/releases/download/Gnuastro-v0.14.0+0/Gnuastro.v0.14.0.x86_64-linux-musl.tar.gz"
[[Gnuastro]]
arch = "x86_64"
git-tree-sha1 = "92d83e2ad55f432d5010bd8c8afba1e50d0434e9"
os = "freebsd"

    [[Gnuastro.download]]
    sha256 = "811e92c5dd49cf4d66c2cc19c1a2a96331de6375941432b841ffa50f547c19e7"
    url = "https://github.com/JuliaBinaryWrappers/Gnuastro_jll.jl/releases/download/Gnuastro-v0.14.0+0/Gnuastro.v0.14.0.x86_64-unknown-freebsd.tar.gz"
