# Autogenerated wrapper script for Gnuastro_jll for aarch64-linux-musl
export astarithmetic, astconvertt, astconvolve, astcosmiccal, astcrop, astfits, astmatch, astmkcatalog, astmknoise, astmkprof, astnoisechisel, astscript_sort_by_night, astsegment, aststatistics, asttable, astwarp, libgnuastro

using CFITSIO_jll
using GSL_jll
using JpegTurbo_jll
using Libtiff_jll
using LibGit2_jll
using WCS_jll
JLLWrappers.@generate_wrapper_header("Gnuastro")
JLLWrappers.@declare_executable_product(astarithmetic)
JLLWrappers.@declare_executable_product(astconvertt)
JLLWrappers.@declare_executable_product(astconvolve)
JLLWrappers.@declare_executable_product(astcosmiccal)
JLLWrappers.@declare_executable_product(astcrop)
JLLWrappers.@declare_executable_product(astfits)
JLLWrappers.@declare_executable_product(astmatch)
JLLWrappers.@declare_executable_product(astmkcatalog)
JLLWrappers.@declare_executable_product(astmknoise)
JLLWrappers.@declare_executable_product(astmkprof)
JLLWrappers.@declare_executable_product(astnoisechisel)
JLLWrappers.@declare_executable_product(astscript_sort_by_night)
JLLWrappers.@declare_executable_product(astsegment)
JLLWrappers.@declare_executable_product(aststatistics)
JLLWrappers.@declare_executable_product(asttable)
JLLWrappers.@declare_executable_product(astwarp)
JLLWrappers.@declare_library_product(libgnuastro, "libgnuastro.so.12")
function __init__()
    JLLWrappers.@generate_init_header(CFITSIO_jll, GSL_jll, JpegTurbo_jll, Libtiff_jll, LibGit2_jll, WCS_jll)
    JLLWrappers.@init_executable_product(
        astarithmetic,
        "bin/astarithmetic",
    )

    JLLWrappers.@init_executable_product(
        astconvertt,
        "bin/astconvertt",
    )

    JLLWrappers.@init_executable_product(
        astconvolve,
        "bin/astconvolve",
    )

    JLLWrappers.@init_executable_product(
        astcosmiccal,
        "bin/astcosmiccal",
    )

    JLLWrappers.@init_executable_product(
        astcrop,
        "bin/astcrop",
    )

    JLLWrappers.@init_executable_product(
        astfits,
        "bin/astfits",
    )

    JLLWrappers.@init_executable_product(
        astmatch,
        "bin/astmatch",
    )

    JLLWrappers.@init_executable_product(
        astmkcatalog,
        "bin/astmkcatalog",
    )

    JLLWrappers.@init_executable_product(
        astmknoise,
        "bin/astmknoise",
    )

    JLLWrappers.@init_executable_product(
        astmkprof,
        "bin/astmkprof",
    )

    JLLWrappers.@init_executable_product(
        astnoisechisel,
        "bin/astnoisechisel",
    )

    JLLWrappers.@init_executable_product(
        astscript_sort_by_night,
        "bin/astscript-sort-by-night",
    )

    JLLWrappers.@init_executable_product(
        astsegment,
        "bin/astsegment",
    )

    JLLWrappers.@init_executable_product(
        aststatistics,
        "bin/aststatistics",
    )

    JLLWrappers.@init_executable_product(
        asttable,
        "bin/asttable",
    )

    JLLWrappers.@init_executable_product(
        astwarp,
        "bin/astwarp",
    )

    JLLWrappers.@init_library_product(
        libgnuastro,
        "lib/libgnuastro.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
